"""
labels.py — Transparency label generation for Provenance Guard.

Three primary variants:
  HIGH_AI       (confidence >= 0.75)
  UNCERTAIN     (confidence 0.35–0.74)
  HIGH_HUMAN    (confidence < 0.35)

Labels use plain language — no jargon.
"""


def generate_label(confidence: float, attribution: str, insufficient_length: bool = False) -> dict:
    """
    Returns a label dict with:
      variant: str (HIGH_AI | UNCERTAIN | HIGH_HUMAN)
      headline: str
      body: str
      confidence_display: str
      show_appeal_prompt: bool
    """
    score_pct = round(confidence * 100)

    if insufficient_length:
        return {
            "variant": "UNCERTAIN",
            "headline": "❓ Attribution Unclear",
            "body": (
                "This content is too short for our system to make a reliable determination. "
                "Please submit a longer piece for a more meaningful analysis. "
                "We've marked it as uncertain rather than risk a misleading result."
            ),
            "confidence_display": f"Confidence: LOW  |  Score: {score_pct}%",
            "show_appeal_prompt": False,
        }

    if confidence >= 0.75:
        return {
            "variant": "HIGH_AI",
            "headline": "⚠️ Likely AI-Generated",
            "body": (
                "Our analysis found strong indicators that this content may have been "
                "generated by an AI tool. This label is shown when multiple detection "
                "signals agree with high confidence.\n\n"
                "If you wrote this yourself, you can submit an appeal below. "
                "Appeals are reviewed by our team within 48 hours."
            ),
            "confidence_display": f"Confidence: HIGH  |  Score: {score_pct}%",
            "show_appeal_prompt": True,
        }
    elif confidence >= 0.35:
        return {
            "variant": "UNCERTAIN",
            "headline": "❓ Attribution Unclear",
            "body": (
                "Our system analyzed this content but could not confidently determine "
                "whether it was written by a person or generated by an AI tool. "
                "This may reflect a unique writing style, mixed-origin content, "
                "or the limits of our detection.\n\n"
                "If you are the human author, you can submit an appeal to have "
                "this reviewed by our team."
            ),
            "confidence_display": f"Confidence: UNCERTAIN  |  Score: {score_pct}%",
            "show_appeal_prompt": True,
        }
    else:
        return {
            "variant": "HIGH_HUMAN",
            "headline": "✅ Appears Human-Written",
            "body": (
                "Our analysis found strong indicators that this content was written "
                "by a person. Multiple signals consistent with human authorship "
                "were detected."
            ),
            "confidence_display": f"Confidence: HIGH  |  Score: {score_pct}%",
            "show_appeal_prompt": False,
        }


def format_label_text(label: dict) -> str:
    """Return the full label as a single display string."""
    return f"{label['headline']}\n{label['body']}\n\n{label['confidence_display']}"


def generate_certificate_label(certificate_id: str, verification_method: str) -> dict:
    """
    Label displayed on content that has earned a Provenance Certificate.
    Visually distinct from the standard transparency label.
    """
    return {
        "variant": "VERIFIED_HUMAN",
        "headline": "🏅 Verified Human-Written",
        "body": (
            "This creator has completed an additional verification step confirming "
            "this work is their own original writing. "
            f"Verified via: {verification_method.replace('_', ' ').title()}."
        ),
        "confidence_display": "Status: VERIFIED",
        "certificate_id": certificate_id,
        "show_appeal_prompt": False,
    }
