"""
signals.py — Detection signals for Provenance Guard.

Signal 1: LLM Classification (Groq)         weight=0.50
Signal 2: Stylometric Heuristics            weight=0.30
Signal 3: Burstiness / Perplexity Proxy     weight=0.20
"""

import math
import os
import re
import string
from groq import Groq

# ─────────────────────────────────────────────
# Signal 1: LLM Classification via Groq
# ─────────────────────────────────────────────

def groq_signal(text: str) -> tuple[float, str]:
    """
    Ask Groq to assess whether text is human- or AI-generated.

    Returns:
        ai_probability (float 0.0–1.0): higher = more likely AI
        reasoning (str): brief explanation from the model
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""You are an expert in distinguishing human-written text from AI-generated text.
Analyze the following text and estimate the probability (0.0 to 1.0) that it was generated by an AI tool.

Return ONLY a JSON object with exactly these two fields:
- "ai_probability": a float between 0.0 and 1.0 (1.0 = definitely AI, 0.0 = definitely human)
- "reasoning": a single sentence explaining the key indicator that drove your score

Consider:
- Overuse of transitional phrases ("furthermore", "it is important to note", "additionally")
- Unnaturally uniform sentence structure and length
- Lack of personal voice, concrete specificity, or emotional irregularity
- Topic coverage that feels systematically complete rather than personally selective
- Hedging language that feels formulaic rather than genuinely uncertain

TEXT TO ANALYZE:
\"\"\"
{text[:3000]}
\"\"\"

Respond ONLY with valid JSON. No markdown, no explanation outside the JSON."""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        raw = re.sub(r"```json\s*|\s*```", "", raw).strip()
        import json
        parsed = json.loads(raw)
        prob = float(parsed.get("ai_probability", 0.5))
        prob = max(0.0, min(1.0, prob))
        reasoning = str(parsed.get("reasoning", "No reasoning provided."))
        return prob, reasoning
    except Exception as e:
        # Fallback: return 0.5 with error note
        return 0.5, f"LLM signal unavailable: {str(e)[:100]}"


# ─────────────────────────────────────────────
# Signal 2: Stylometric Heuristics
# ─────────────────────────────────────────────

def _split_sentences(text: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s for s in sentences if len(s.split()) >= 2]


def _sentence_length_variance_score(sentences: list[str]) -> float:
    """Low variance → AI-like. Returns 0–1 (1 = AI)."""
    if len(sentences) < 3:
        return 0.5
    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    if mean == 0:
        return 0.5
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    cv = std_dev / mean  # coefficient of variation
    # Human writing: cv typically 0.4–1.0. AI: 0.1–0.35
    ai_score = max(0.0, min(1.0, 1.0 - (cv / 0.6)))
    return round(ai_score, 4)


def _type_token_ratio_score(text: str) -> float:
    """
    Lower TTR in long texts is human-like (repetition, idioms).
    AI tends to have artificially diverse vocabulary.
    Returns 0–1 (1 = AI).
    """
    words = re.findall(r"\b[a-z']+\b", text.lower())
    if len(words) < 10:
        return 0.5
    ttr = len(set(words)) / len(words)
    # AI text: 0.55–0.80 TTR. Human casual: 0.30–0.55
    # High TTR → more AI-like in this context
    ai_score = max(0.0, min(1.0, (ttr - 0.3) / 0.5))
    return round(ai_score, 4)


def _punctuation_density_score(text: str, sentences: list[str]) -> float:
    """
    AI text has more uniform punctuation. Humans use em-dashes,
    ellipses, and varied comma usage stylistically.
    Returns 0–1 (1 = AI / too uniform).
    """
    if not sentences:
        return 0.5
    # Count per-sentence comma density
    comma_counts = [s.count(",") / max(len(s.split()), 1) for s in sentences]
    if len(comma_counts) < 3:
        return 0.5
    mean = sum(comma_counts) / len(comma_counts)
    variance = sum((c - mean) ** 2 for c in comma_counts) / len(comma_counts)
    std_dev = math.sqrt(variance)
    # Low std_dev relative to mean → uniform → AI
    cv = std_dev / (mean + 0.001)
    ai_score = max(0.0, min(1.0, 1.0 - (cv / 0.5)))
    return round(ai_score, 4)


def _formality_score(text: str) -> float:
    """
    AI text skews formal. Contractions, first-person casual markers → human.
    Returns 0–1 (1 = AI / highly formal).
    """
    text_lower = text.lower()
    word_count = max(len(text_lower.split()), 1)

    # Informal markers (lower score = more human)
    contractions = len(re.findall(
        r"\b(i'm|i've|i'd|i'll|don't|won't|can't|couldn't|wouldn't|shouldn't|"
        r"it's|that's|there's|they're|we're|you're|didn't|wasn't|isn't|aren't)\b",
        text_lower
    ))
    filler_words = len(re.findall(
        r"\b(honestly|literally|basically|actually|anyway|like|just|ok|okay|yeah|nah|hmm)\b",
        text_lower
    ))
    informal_score = (contractions + filler_words) / word_count

    # Formal markers (higher score = more AI)
    formal_phrases = len(re.findall(
        r"\b(furthermore|additionally|moreover|consequently|therefore|nevertheless|"
        r"it is important to note|it should be noted|in conclusion|in summary|"
        r"it is worth noting|this highlights|this underscores|plays a crucial role|"
        r"a wide range of|various aspects|in today's|in the modern|stakeholders)\b",
        text_lower
    ))
    formal_score = formal_phrases / word_count

    ai_score = max(0.0, min(1.0, (formal_score * 15) - (informal_score * 10) + 0.4))
    return round(ai_score, 4)


def stylometric_signal(text: str) -> float:
    """
    Combine 4 stylometric sub-signals into a single 0–1 score.
    Higher = more AI-like.
    Weights: sentence_variance(0.35) + TTR(0.20) + punctuation(0.20) + formality(0.25)
    """
    sentences = _split_sentences(text)

    slv = _sentence_length_variance_score(sentences)
    ttr = _type_token_ratio_score(text)
    pds = _punctuation_density_score(text, sentences)
    fml = _formality_score(text)

    combined = (slv * 0.35) + (ttr * 0.20) + (pds * 0.20) + (fml * 0.25)
    return round(combined, 4), {
        "sentence_length_variance_score": slv,
        "type_token_ratio_score": ttr,
        "punctuation_density_score": pds,
        "formality_score": fml,
    }


# ─────────────────────────────────────────────
# Signal 3: Burstiness / Perplexity Proxy
# ─────────────────────────────────────────────

def _burstiness_index(sentences: list[str]) -> float:
    """
    Burstiness = (std - mean) / (std + mean) for sentence lengths.
    Human: burstiness > 0.0. AI: burstiness < 0.0 (too uniform).
    Returns 0–1 AI score (1 = AI/uniform, 0 = human/bursty).
    """
    if len(sentences) < 4:
        return 0.5
    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    if mean == 0:
        return 0.5
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std = math.sqrt(variance)
    burstiness = (std - mean) / (std + mean + 1e-9)
    # burstiness < 0 → uniform (AI); > 0 → bursty (human)
    # Map to 0–1 AI score: burstiness=-1 → 1.0, burstiness=1 → 0.0
    ai_score = max(0.0, min(1.0, (1.0 - burstiness) / 2.0))
    return round(ai_score, 4)


def _rare_word_distribution_score(text: str) -> float:
    """
    Human writers cluster rare/unusual words in emotionally charged moments.
    AI distributes rare words evenly throughout.
    We approximate by comparing rare-word density in first vs second half.
    Returns 0–1 (1 = AI / evenly distributed, 0 = human / clustered).
    """
    words = re.findall(r"\b[a-z]{5,}\b", text.lower())
    if len(words) < 20:
        return 0.5

    # Common words (top ~1000 English) — approximate by word length heuristic
    # Short common words are usually not rare; long specialized words are rarer
    rare_words = [w for w in words if len(w) >= 8]
    if not rare_words:
        return 0.3  # Very common vocabulary → mildly human-like

    half = len(words) // 2
    first_half_words = words[:half]
    second_half_words = words[half:]

    first_rare = sum(1 for w in first_half_words if w in rare_words) / (len(first_half_words) + 1)
    second_rare = sum(1 for w in second_half_words if w in rare_words) / (len(second_half_words) + 1)

    ratio = min(first_rare, second_rare) / (max(first_rare, second_rare) + 1e-9)
    # ratio near 1.0 = evenly distributed = AI-like
    return round(ratio, 4)


def _paragraph_variance_score(text: str) -> float:
    """
    AI text tends to have similar-length paragraphs.
    Human writing has high paragraph length variance.
    Returns 0–1 (1 = AI / uniform paragraphs).
    """
    paragraphs = [p.strip() for p in text.split("\n\n") if len(p.strip()) > 20]
    if len(paragraphs) < 2:
        return 0.5
    lengths = [len(p.split()) for p in paragraphs]
    mean = sum(lengths) / len(lengths)
    if mean == 0:
        return 0.5
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std = math.sqrt(variance)
    cv = std / mean
    # Low CV → uniform → AI
    ai_score = max(0.0, min(1.0, 1.0 - (cv / 0.8)))
    return round(ai_score, 4)


def burstiness_signal(text: str) -> tuple[float, dict]:
    """
    Combine 3 burstiness/perplexity-proxy sub-signals.
    Weights: burstiness(0.50) + rare_word_dist(0.25) + paragraph_var(0.25)
    """
    sentences = _split_sentences(text)
    bi = _burstiness_index(sentences)
    rwd = _rare_word_distribution_score(text)
    pvs = _paragraph_variance_score(text)

    combined = (bi * 0.50) + (rwd * 0.25) + (pvs * 0.25)
    return round(combined, 4), {
        "burstiness_index_score": bi,
        "rare_word_distribution_score": rwd,
        "paragraph_variance_score": pvs,
    }


# ─────────────────────────────────────────────
# Ensemble: Combine All Three Signals
# ─────────────────────────────────────────────

SIGNAL_WEIGHTS = {
    "llm": 0.50,
    "stylometric": 0.30,
    "burstiness": 0.20,
}


def combine_scores(llm_score: float, stylometric_score: float, burstiness_score: float) -> float:
    """
    Weighted ensemble of three signals → single confidence float.
    Higher = more confident the text is AI-generated.
    """
    combined = (
        llm_score * SIGNAL_WEIGHTS["llm"]
        + stylometric_score * SIGNAL_WEIGHTS["stylometric"]
        + burstiness_score * SIGNAL_WEIGHTS["burstiness"]
    )
    return round(max(0.0, min(1.0, combined)), 4)


def attribution_from_confidence(confidence: float) -> str:
    if confidence >= 0.60:
        return "likely_ai"
    elif confidence <= 0.40:
        return "likely_human"
    else:
        return "uncertain"


# ─────────────────────────────────────────────
# Metadata Signal (Multi-modal stretch)
# ─────────────────────────────────────────────

AI_SOFTWARE_TAGS = {
    "stable diffusion", "midjourney", "dall-e", "dall·e", "firefly",
    "imagen", "nightcafe", "dreamstudio", "leonardo", "adobe firefly",
    "runway", "bing image creator", "adobe generative fill"
}


def metadata_signal(metadata: dict) -> tuple[float, list[str]]:
    """
    Analyze image/file metadata for AI-generation indicators.
    Returns: (ai_probability 0–1, list of flag strings)
    """
    flags = []
    score = 0.0

    software = str(metadata.get("software", "") or metadata.get("Software", "")).lower()
    for tag in AI_SOFTWARE_TAGS:
        if tag in software:
            flags.append(f"AI software tag detected: '{software}'")
            score += 0.90
            break

    # Missing camera model is suspicious for images
    camera_model = metadata.get("camera_model") or metadata.get("Model") or metadata.get("model")
    if not camera_model:
        flags.append("No camera model in metadata")
        score += 0.15

    # Missing GPS when other EXIF data present
    has_exif = any(k in metadata for k in ["Make", "Model", "DateTime", "ExposureTime"])
    has_gps = any(k in metadata for k in ["GPSLatitude", "GPSLongitude", "gps_lat", "gps_lon"])
    if has_exif and not has_gps:
        flags.append("EXIF data present but no GPS coordinates")
        score += 0.10

    # Creation/modification timestamps too close (AI generates both simultaneously)
    created = metadata.get("created_at") or metadata.get("DateTimeOriginal")
    modified = metadata.get("modified_at") or metadata.get("DateTime")
    if created and modified and created == modified:
        flags.append("Creation and modification timestamps are identical")
        score += 0.20

    # Explicit AI prompt field
    if metadata.get("prompt") or metadata.get("ai_prompt"):
        flags.append("AI prompt field present in metadata")
        score += 1.0

    return round(min(1.0, score), 4), flags
